# -*- coding: utf-8 -*-
# PAGE OBJECTS FILE >>> (autogenerated)


class Page(object):
    subarray_1 = (
            '//*[@id="ui-view-container-div"]/div/div[1]/div/div[1]/div/button[1]'
        )
    back_drop = '//*[@id="main-top-toolbar"]/div/span'
    alarm_sounds = (
        "body > md-content > md-sidenav.md-sidenav-right._md.md-deep-purple-theme."
        "layout-column > md-content > md-list > md-item:nth-child(5) > "
        "md-item-content:nth-child(4) > md-checkbox > div.md-container.md-ink-ripple"
    )
    alarm_notification = (
        "body > md-content > md-sidenav.md-sidenav-right._md.md-deep-"
        "purple-theme.layout-column > md-content > md-list > md-item:nth-child(5) > "
        "md-item-content:nth-child(2) > md-checkbox > div.md-label"
    )
    user_icon = "#main-top-toolbar > div > button:nth-child(7) > span"
    enter_input = "#input_1"
    expert = "#select_option_6"
    html = "html"
    select_user = "#select_value_label_0"
    submit_button = "#ui-view-container-div > div > form > button"
    user_email = "enter_email"
    user_pass = "#input_2"
